ktor:
  application:
    modules:
      - com.example.MainKt.module
  deployment:
    port: 9090

database:
  driverClassName: "com.mysql.cj.jdbc.Driver"
  jdbcURL: "jdbc:mysql://localhost:3306/app?useUnicode=true&characterEncoding=utf8&useSSL=false"
  username: "root"
  password: ""
  maximumPoolSize: 10

security:
  password:
    pbkdf2:
      algorithm: "PBKDF2WithHmacSHA256"
      iterations: "120000"
      keyLength: "256"
      saltLength: "16"
  paseto:
    issuer: "time-capsule-alpha"
    privateKey: "MC4CAQAwBQYDK2VwBCIEIBJbj0ZFnNxYANH/fpzO5+LQGE2Djiv3wysZM93OWPNq"
    publicKey: "MCowBQYDK2VwAyEAlZyrtYwZn00A91LbCzjX4YN56AvAqa7AuETEfNPhlDY="
  timebase:
    masterKey : cTjzOEZNpXees+RZMGzvDQmnIPlURWEn+brd9yi0Qro=

storage:
  type: "minio"  # "minio" 또는 "s3"
  minio:
    endpoint: "http://localhost:9000"
    accessKey: "minio_user"
    secretKey: "minio_password"
  s3:
    endpoint: "https://s3.amazonaws.com"
    region: "us-east-1"
    accessKey: "access"
    secretKey: "secret"