ktor:
  application:
    modules:
      - com.example.MainKt.module
  deployment:
    port: 9090

database:
  driverClassName: "com.mysql.cj.jdbc.Driver"
  jdbcURL: "jdbc:mysql://localhost:3306/app?useUnicode=true&characterEncoding=utf8&useSSL=false"
  username: "root"
  password: ""
  maximumPoolSize: 10