ktor:
  application:
    modules:
      - com.example.MainKt.module
  deployment:
    port: 9090

email:
  # 사용할 이메일 공급자 (jakarta-mail 또는 aws-ses)
  provider: jakarta-mail

  fromEmail: ${EMAIL_FROM:noreply@yourcompany.com}
  fromName: ${EMAIL_FROM_NAME:Your Company}
  debugEnabled: ${EMAIL_DEBUG:false}

  jakartaMail:
    host: ${EMAIL_SMTP_HOST:smtp.gmail.com}
    port: ${EMAIL_SMTP_PORT:587}
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    connectionTimeout: ${EMAIL_CONNECTION_TIMEOUT:5000}
    timeout: ${EMAIL_TIMEOUT:5000}

  # AWS SES 설정 (provider=aws-ses일 때 사용)
  awsSes:
    region: ${AWS_SES_REGION:us-east-1}
    accessKey: ${AWS_ACCESS_KEY:}
    secretKey: ${AWS_SECRET_KEY:}

database:
  driverClassName: "com.mysql.cj.jdbc.Driver"
  jdbcURL: "jdbc:mysql://localhost:3306/app?useUnicode=true&characterEncoding=utf8&useSSL=false"
  username: "root"
  password: ""
  maximumPoolSize: 10

security:
  password:
    pbkdf2:
      algorithm: "PBKDF2WithHmacSHA256"
      iterations: "120000"
      keyLength: "256"
      saltLength: "16"
  paseto:
    issuer: "time-capsule-alpha"
    privateKey: "MC4CAQAwBQYDK2VwBCIEIBJbj0ZFnNxYANH/fpzO5+LQGE2Djiv3wysZM93OWPNq"
    publicKey: "MCowBQYDK2VwAyEAlZyrtYwZn00A91LbCzjX4YN56AvAqa7AuETEfNPhlDY="
  timebase:
    masterKey : cTjzOEZNpXees+RZMGzvDQmnIPlURWEn+brd9yi0Qro=

storage:
  type: "minio"  # "minio" 또는 "s3"
  minio:
    endpoint: "http://localhost:9000"
    accessKey: "minio_user"
    secretKey: "minio_password"
  s3:
    endpoint: "https://s3.amazonaws.com"
    region: "us-east-1"
    accessKey: "access"
    secretKey: "secret"